name: Pull request artifacts
on: 
  push:
    paths:
    - ".github/workflows/pr.yml"
    
jobs:
  pullRequest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scen_num: [0, 1, 21, 25]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: data-output-S${{ matrix.scen_num }}
          path: data/output
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add sim output simulation study datagen_scen scen_num ${{ matrix.scen_num }}
          committer: Linda Nab <LindaNab@users.noreply.github.com>
          branch: patch${{ matrix.scen_num }}